### ISSUE TITLE
The package product 'Lottie' requires minimum platform version 11.0, but this target supports 9.0

### ISSUE THREAD

**Issue by mesiser** [dotlottie/dotlottie-ios#10]
What's wrong: swift compiler error after installing dotlottie-ios (pls see issue title)
How to reproduce: install dotlottie through pagackage manager. Try to build

Hi! I wan't able to use dotlottie-ios due to above issue. Looks like the minimum iOS (macOS and tvOS as well) version shall be updated in package platforms.

**Comment by eharrison** [comment]
Hello @mesiser, checking for you!

**Comment by leonardo-ferreira07** [comment]
@mesiser we just have fixed this issue for you, it's in the new release `0.1.9` of `dotlottie-ios` library.

@eharrison we can close this then, right?
