### ISSUE TITLE
Not found dotLottieLoader

### ISSUE THREAD

**Issue by tronuo0** [dotlottie/dotlottie-ios#5]
Hi. This error appears after calling 'pod install'.
Unable to find a specification for `dotLottieLoader (~> 0.1.0)` depended upon by `dotLottie`

**Comment by eharrison** [comment]
Hello @TheTronuo.

Thank you for your comment, we are currently working on a better way to use dotLottie, but in the meantime I've updated the documentation on how to use dotLottie with CocoaPods. Please include both lines to your Podfile:

```
pod 'dotLottie', :git => 'https://github.com/dotlottie/dotlottie-ios.git'
pod 'dotLottieLoader', :git => 'https://github.com/dotlottie/dotlottieLoader-ios.git'
```

Hope this helps. Please let us know if any issue :)
