### ISSUE TITLE
.lottie file is not showing all the contents in animation

### ISSUE THREAD

**Issue by vermamukesh67** [dotlottie/dotlottie-ios#6]
Hello,

i downloaded the sample .lottie file (animation-external-image.lottie & animation-inline-image.lottie) from :(https://dotlottie.io/structure/#sample-dotlottie-files) and used in my sample iOS project but its not working as expected. even though its not working in your sample iOS project. Same thing happened with our own .lottie file.

**iOS Code is as below**

 

@IBOutlet weak var animationView: AnimationView!
    override func viewDidLoad() {
        super.viewDidLoad()
        DotLottie.load(name: "animation-inline-image") { (animation) in
            if let animation = animation {
                self.animationView.animation = animation
                self.animationView.loopMode = .loop
                self.animationView.play()
            } else {
               print("Error loading .lottie")
            }
        }
    }

### **issue** : Not able to see 2020 text with gradients ribbon please see below screenshot highlighted with red arrow.

<img width="910" alt="Screenshot 2021-02-08 at 11 54 42 AM" src="https://user-images.githubusercontent.com/21167777/107176083-5ea42e00-6a09-11eb-94ba-66f05a5c131f.png">

**iOS sample app screenshot** 

![Simulator Screen Shot - iPhone 12 Pro - 2021-02-08 at 12 32 19](https://user-images.githubusercontent.com/21167777/107176426-54366400-6a0a-11eb-83d2-7adb7d3b36e3.png)

**Screenshot for when we use our lottie file, some background resources are not showing**

![Simulator Screen Shot - iPhone 11 Pro - 2021-02-08 at 12 53 34](https://user-images.githubusercontent.com/21167777/107177403-bc864500-6a0c-11eb-9652-1f464e44bf45.png)

**screenshot for result what we expect**

![Simulator Screen Shot - iPhone 11 Pro - 2021-02-08 at 12 49 55](https://user-images.githubusercontent.com/21167777/107177254-65807000-6a0c-11eb-8d33-f371ed5dd5c4.png)

**Comment by eharrison** [comment]
Hello,

Thank you for letting us know of the issue.

We had a dependency on Lottie-iOS, that was not supporting images. It's been fixed there and we I just updated the library to support images.

Please let me know if this fixes your issue :)

<img width="504" alt="image" src="https://user-images.githubusercontent.com/1723967/107205248-9a0a2100-6a38-11eb-9e7d-2462f84de296.png">

It's already available for SPM and will soon be available for CocoaPods.
