### ISSUE TITLE
Wrong resolved issue

### ISSUE THREAD

**Issue by pxlRider** [dotlottie/dotlottie-ios#7]
Lottie change min iOS version to iOS11 in 3.3.0, so using this package now build fails, because it only target iOS9.

**Comment by eharrison** [comment]
Updated the library version as per request. Let us know if you still have any issues :)

**Comment by pxlRider** [comment]
This resolves the issue, can this be put into new release version? Currently only works if I lock package to master branch. Thank you! :)
