### ISSUE TITLE
SwiftUI DotLottieView not found

### ISSUE THREAD

**Issue by daniel-k-marks** [dotlottie/dotlottie-ios#9]
I am trying to follow your ReadMe doc to SwiftUI and DotLottieView but keep getting an error: `Cannot find 'DotLottieView' in scope`.
I tried searching the files and haven't found anything called DotLottieView.

My Code:

    struct LottieView: View {
    
        // MARK: - Properties
    
        @State var name: String
        @State var play: Int = 1
        var completion: ((Bool) -> ())? = nil
    
        // MARK: - UI
    
        var body: some View {
            DotLottieView(name: name, play: self.$play, onCompleted: completion)
        }
    }

**Comment by eharrison** [comment]
Hello,

You may find DotLottieView and how to use it inside the example folder: https://github.com/dotlottie/dotlottie-ios/blob/master/Example/dotLottie/SwiftUI/DotLottieView.swift
